name: Build and Publish Packages

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y rpm dpkg-dev

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build release
        run: cargo build --release --verbose

      - name: Generate .deb package
        run: |
          cargo install cargo-deb
          cargo deb

      - name: Generate .rpm package
        run: |
          cargo install cargo-generate-rpm
          cargo generate-rpm

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: built-packages
          path: |
            target/debian/*.deb
            target/generate-rpm/*.rpm

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download built packages
        uses: actions/download-artifact@v4
        with:
          name: built-packages
          path: artifacts

      - name: List contents of artifacts directory
        run: ls -la artifacts/

      - name: Extract artifacts if compressed
        run: |
          if [ -f artifacts/built-packages.zip ]; then
            unzip artifacts/built-packages.zip -d artifacts/
          fi

      - name: Verify files after extraction
        run: ls -la artifacts/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Authenticate with GitHub Container Registry
        run: echo "${{ secrets.GH_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Publish .deb package to GitHub Container Registry
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          for file in artifacts/debian/*.deb; do
            package_name="clipboardmonitor"  # Sin mayúsculas ni guiones
            package_version=$(dpkg-deb --showformat='${Version}' --show "$file" | tr '-' '_')  # Sustituye "-" por "_"
            
            echo "Preparando paquete $file para ghcr.io/kdonjs/$package_name:$package_version"
          
            # Crear una imagen de contenedor temporal
            mkdir -p temp_package
            cp "$file" temp_package/
            cd temp_package
            echo "FROM scratch" > Dockerfile
            echo "COPY . /" >> Dockerfile
            
            image_name="ghcr.io/kdonjs/$package_name:$package_version"

            docker build -t "$image_name" .
            docker push "$image_name"

            cd ..
            rm -rf temp_package
          done

      - name: Publish .rpm package to GitHub Container Registry
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          for file in artifacts/generate-rpm/*.rpm; do
            package_name="clipboardmonitor"  # Sin mayúsculas ni guiones
            package_version=$(rpm -qp --queryformat '%{VERSION}-%{RELEASE}' "$file" | tr '-' '_')  # Sustituye "-" por "_"
            
            echo "Preparando paquete $file para ghcr.io/kdonjs/$package_name:$package_version"

            # Crear una imagen de contenedor temporal
            mkdir -p temp_package
            cp "$file" temp_package/
            cd temp_package
            echo "FROM scratch" > Dockerfile
            echo "COPY . /" >> Dockerfile

            image_name="ghcr.io/kdonjs/$package_name:$package_version"

            docker build -t "$image_name" .
            docker push "$image_name"

            cd ..
            rm -rf temp_package
          done