name: Build and Release Rust App

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y rpm

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Build release
      run: cargo build --release --verbose

    - name: Generate .deb
      run: |
        cargo install cargo-deb
        cargo deb

    - name: Generate .rpm
      run: |
        cargo install cargo-generate-rpm
        cargo generate-rpm

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: built-packages
        path: |
          target/debian/*.deb
          target/generate-rpm/*.rpm

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download built packages
      uses: actions/download-artifact@v4
      with:
        name: built-packages
        path: artifacts

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: artifacts/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
