name: Build and Release Rust App

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libssl-dev pkg-config

      - name: Build
        run: cargo build --release

      - name: Package Debian
        run: |
          mkdir -p artifacts/debian
          cargo install cargo-deb
          cargo deb --output artifacts/debian/

      - name: Package RPM
        run: |
          mkdir -p artifacts/rpm
          cargo install cargo-generate-rpm
          cargo generate-rpm --release
          cp target/release/rpmbuild/RPMS/*/*.rpm artifacts/rpm/

      - name: Upload built packages
        uses: actions/upload-artifact@v4
        with:
          name: built-packages
          path: artifacts/**/*

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download built packages
        uses: actions/download-artifact@v4
        with:
          name: built-packages
          path: artifacts

      - name: Validate downloaded artifacts
        run: |
          echo "Archivos descargados:"
          ls -l artifacts/
          if [ -z "$(ls -A artifacts/)" ]; then
            echo "Error: No se encontraron artefactos descargados."
            exit 1
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}